# Generated by Django 3.0.1 on 2020-10-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockname', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('value', models.IntegerField()),
                ('action', models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], default='BUY', max_length=30)),
            ],
        ),
    ]
