# Generated by Django 3.0.1 on 2020-10-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20201010_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
