# Generated by Django 3.0.1 on 2020-10-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_userstock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='action',
            field=models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstock',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
