# Generated by Django 3.0.1 on 2020-10-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20201010_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstock',
            name='action',
        ),
    ]
