# Generated by Django 3.0.1 on 2020-10-11 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_remove_userstock_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstock',
            name='value',
        ),
    ]
