# Generated by Django 3.0.1 on 2020-10-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_remove_userstock_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='username',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
