# Generated by Django 3.0.1 on 2020-10-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_auto_20201010_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='action',
            field=models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userstock',
            name='lastprice',
            field=models.FloatField(),
        ),
    ]
