# Generated by Django 3.0.1 on 2020-10-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
