# Generated by Django 3.0.1 on 2020-10-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_auto_20201011_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('stockname', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'unique_together': {('username', 'stockname')},
            },
        ),
    ]
