# Generated by Django 3.0.1 on 2020-10-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_auto_20201011_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockquantity',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
