# Generated by Django 3.0.1 on 2020-10-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_auto_20201011_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstock',
            name='cashvalue',
        ),
        migrations.AlterField(
            model_name='cash',
            name='cashvalue',
            field=models.FloatField(default=10000),
        ),
    ]
